### ISSUE TITLE
Is pagination supported?

### ISSUE THREAD

**Issue by bperel** [givka/bedetheque-scraper#5]
When fetching the details of a series, only the first 10 albums are sent back. Is there a way to either specify that all the albums should be retrieved, or to indicate pagination data (offset + limit)?

**Comment by givka** [comment]
My bad, normally it should retrieve all the albums.
In order to do this, you have to change : https://www.bedetheque.com/serie-8372-BD-Tintin.html with https://www.bedetheque.com/serie-8372-BD-Tintin__10000.html.
It was added automatically when fetching urls from `Scraper.getSeriesUrlFromLetter(letter)`.
I will add this to be the default in `Scraper.getSerie(serieUrl)`.

**Comment by givka** [comment]
Fixed in 2.9.1
